bastion:
  hosts:
    anubhavg_bastion:
      ansible_host: 10.0.1.10
code:
  hosts:
    code_server:
      ansible_host: 10.0.8.10
firewall:
  hosts:
    opnsense:
      ansible_host: 10.0.1.1
nas:
  hosts:
    anubhavg_nas:
      ansible_host: 10.0.11.10
servarr:
  hosts: 10.0.10.10
dns:
  hosts:
    primary_dns:
      ansible_host: 10.0.7.2
      dns_user: dns
    backup_dns:
      ansible_host: 10.0.7.3
      dns_user: dns-1
streaming:
  hosts: 10.0.0.19
torrent:
  hosts: 10.0.6.10
hypervisors:
  hosts:
    freedom:
      ansible_host: 10.0.1.254
security:
  hosts:
    security_vm:
      ansible_host: 10.0.0.10
reverse_proxy:
  hosts:
    private_reverse_proxy:
      ansible_host: 10.0.4.10
      reverse_proxy_user: reverse-proxy
      groups: 'internet_facing,trusted'
vmware:
  hosts:
    vmware_host:
      ansible_host: 10.0.0.11
knowledge_management:
  hosts:
    knowledge:
      ansible_host: 10.0.0.13
vps:
  hosts:
    vps_hetzner:
      ansible_host: '192.168.1.100'
