---
all:
  children:
    wazuh_manager:
      hosts:
        wazuh01:
          ansible_host: 192.168.1.10  # Replace with your actual host IP
      vars:
        wazuh_user: wazuh
        wazuh_network: wazuh
        wazuh_certs_dir: '/var/wazuh'
