- name: Configure bastion virtual machine
  hosts: bastion
  vars:
    bastion_user: bastion
    bastion_guacamole_network: guacamole
    bastion_guacamole_postgres_db: guacamole_postgres
    bastion_guacamole_postgres_user: 'guacamole_user'
    bastion_guacamole_postgres_pass: 'DB_Guac#pL5$nK8vM3@bX7&rQ4wY9zT6'
    bastion_guacamole_postgres_init_dir: /var/guacamole_web
  tasks:
    - name: Ensure /etc/hosts is configured
      ansible.builtin.import_role:
        name: dynamic_hosts

    - name: Ensure there's a virtual network for Apache Guacamole
      ansible.builtin.import_role:
        name: podman
        tasks_from: network
      vars:
        podman_network: '{{ bastion_guacamole_network }}'
        podman_user: '{{ bastion_user }}'

    - name: Ensure Guacamole database init script is present
      ansible.builtin.import_role:
        name: guacamole_web
        tasks_from: initdb.yml
      vars:
        guacamole_web_user: '{{ bastion_user }}'
        guacamole_web_initdb_path: '{{ bastion_guacamole_postgres_init_dir }}'

    - name: Deploy Postgres for Guacamole
      ansible.builtin.import_role:
        name: postgres
      vars:
        postgres_podman_user: '{{ bastion_user }}'
        postgres_container: '{{ bastion_guacamole_postgres_db }}'
        postgres_data_vol: 'guacamole_postgres'
        postgres_db: '{{ bastion_guacamole_postgres_db }}'
        postgres_user: '{{ bastion_guacamole_postgres_user }}'
        postgres_pass: '{{ bastion_guacamole_postgres_pass }}'
        postgres_network: '{{ bastion_guacamole_network }}'
        postgres_init_script: '{{ bastion_guacamole_postgres_init_dir }}/initdb.sql'

    - name: Deploy Guacamole guacd
      ansible.builtin.import_role:
        name: guacamole_guacd
      vars:
        guacamole_guacd_user: '{{ bastion_user }}'
        guacamole_guacd_container: guacamole_guacd
        guacamole_guacd_network: '{{ bastion_guacamole_network }}'

    - name: Deploy Guacamole web
      ansible.builtin.import_role:
        name: guacamole_web
      vars:
        guacamole_web_user: '{{ bastion_user }}'
        guacamole_web_port: '8081'
        guacamole_web_container: guacamole_web
        guacamole_web_network: '{{ bastion_guacamole_network }}'
        guacamole_web_guacd_hostname: guacamole_guacd
        guacamole_web_extension_priority: 'postgresql, openid'
        guacamole_web_openid_authorization_endpoint: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ anubhavg_realm }}/protocol/openid-connect/auth'
        guacamole_web_openid_jwks_endpoint: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ anubhavg_realm }}/protocol/openid-connect/certs'
        guacamole_web_openid_issuer: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ anubhavg_realm }}'
        guacamole_web_openid_client_id: '{{ remote_client }}'
        guacamole_web_openid_redirect_uri: 'https://{{ remote_host }}.{{ internet_host }}'
        guacamole_web_pg_host: '{{ bastion_guacamole_postgres_db }}'
        guacamole_web_pg_db: '{{ bastion_guacamole_postgres_db }}'
        guacamole_web_pg_user: '{{ bastion_guacamole_postgres_user }}'
        guacamole_web_pg_pass: '{{ bastion_guacamole_postgres_pass }}'
