- name: Configure Code virtual machine
  hosts: code
  vars:
    code_user: code

  tasks:
    - name: Configure VM network interfaces
      ansible.builtin.import_role:
        name: base_vm
        tasks_from: network
      vars:
        base_vm_network_interfaces:
          - name: 'eth0'
            mtu: '9000'

    - name: Deploy personal code-server
      ansible.builtin.import_role:
        name: code_server
      vars:
        code_server_user: '{{ code_user }}'
        code_server_container: code-server-personal
        code_server_image: code-server-personal
        code_server_http_port: '8443'
        code_server_sudo_pass: 'CODE_Sudo#nP5$mK8vL3@bR7&xQ4wY9'
        code_server_proxy_domain: '{{ code_personal_host }}.{{ internet_host }}'
        code_server_workspace: code_server_personal
        code_server_extra_pkgs:
          - git
          - curl
          - wget
          - python3-pip
          - ansible
          - ansible-lint
          - direnv
          - telnet
          - inetutils-ping
          - zip
          - unzip
          - dnsutils

    - name: Deploy work code-server
      ansible.builtin.import_role:
        name: code_server
      vars:
        code_server_user: '{{ code_user }}'
        code_server_container: code-server-work
        code_server_image: code-server-work
        code_server_http_port: '8444'
        code_server_sudo_pass: 'CODE_Sudo#nP5$mK8vL3@bR7&xQ4wY9'
        code_server_proxy_domain: '{{ code_work_host }}.{{ internet_host }}'
        code_server_workspace: code_server_work
        code_server_extra_pkgs:
          - git
          - curl
          - direnv
          - telnet
          - inetutils-ping
          - zip
          - unzip
          - python3-pip
          - dnsutils

    - name: Deploy oauth2_proxy for work code_server
      ansible.builtin.import_role:
        name: oauth2_proxy
      vars:
        oauth2_proxy_user: '{{ code_user }}'
        oauth2_proxy_container: 'code-server-work-oauth2-proxy'
        oauth2_proxy_port: '4180'
        oauth2_proxy_email_domains: '*'
        oauth2_proxy_reverse: 'true'
        oauth2_proxy_cookie_secret: 'OAUTH_Cookie#kL7$mN4vR9@bP5&xQ8wY3'
        oauth2_proxy_whitelist_domains: "['.{{ internet_host }}']"
        oauth2_proxy_cookie_domains: "['.{{ internet_host }}']"
        oauth2_proxy_provider: '{{ homelab_oidc_provider }}'
        oauth2_proxy_client_id: '{{ code_client }}'
        oauth2_proxy_client_secret: '{{ code_secret }}'
        oauth2_proxy_redirect_url: 'https://{{ code_work_host }}.{{ internet_host }}/oauth2/callback'
        oauth2_proxy_oidc_url: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}'
        oauth2_proxy_allow_unverified_email: 'true'

    - name: Deploy oauth2_proxy for personal code_server
      ansible.builtin.import_role:
        name: oauth2_proxy
      vars:
        oauth2_proxy_user: '{{ code_user }}'
        oauth2_proxy_container: 'code-server-personal-oauth2-proxy'
        oauth2_proxy_port: '4181'
        oauth2_proxy_email_domains: '*'
        oauth2_proxy_reverse: 'true'
        oauth2_proxy_cookie_secret: 'OAUTH_Cookie#kL7$mN4vR9@bP5&xQ8wY3'
        oauth2_proxy_whitelist_domains: "['.{{ internet_host }}']"
        oauth2_proxy_cookie_domains: "['.{{ internet_host }}']"
        oauth2_proxy_provider: '{{ homelab_oidc_provider }}'
        oauth2_proxy_client_id: '{{ code_client }}'
        oauth2_proxy_client_secret: '{{ code_secret }}'
        oauth2_proxy_redirect_url: 'https://{{ code_personal_host }}.{{ internet_host }}/oauth2/callback'
        oauth2_proxy_oidc_url: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}'
        oauth2_proxy_allow_unverified_email: 'true'

    - name: Deploy Wazuh agent
      ansible.builtin.import_role:
        name: wazuh_agent
      vars:
        wazuh_agent_version: '4.x'
        wazuh_agent_manager_host: '{{ siem_host }}'
        wazuh_agent_registration_pass: '{{ siem_enrollment_pass }}'
        wazuh_agent_name: 'code'
        wazuh_agent_groups: 'internet_facing,trusted'
