- name: Configure knowledge virtual machine
  hosts: knowledge
  vars:
    knowledge_user: knowledge
    knowledge_network: knowledge
    knowledge_data: /var/knowledge
    knowledge_wikijs_pgpass: 'DB_Wiki#kP8$mL5vR3@bN7&xQ4wY9zT6'
  tasks:
    - name: NFS volumes configuration
      ansible.builtin.import_role:
        name: nfs_client
      vars:
        nfs_client_user: "{{ knowledge_user }}"
        nfs_client_mounts: {
          "{{nas_host}}:{{ nfs_server_data }}/knowledge": "{{ knowledge_data }}"
        }

    - name: Ensure there's a virtual network for knowledge
      ansible.builtin.import_role:
        name: podman
        tasks_from: network
      vars:
        podman_user: "{{ knowledge_user }}"
        podman_network: "{{ knowledge_network }}"

    - name: Deploy Postgres for WikiJS
      ansible.builtin.import_role:
        name: postgres
      vars:
        postgres_podman_user: "{{ knowledge_user }}"
        postgres_container: postgres
        postgres_data_dir: "{{ knowledge_data }}"
        # postgres_data_vol: knowledge
        postgres_db: wikijs
        postgres_user: wikijs
        postgres_network: "{{ knowledge_network }}"
        postgres_pass: "{{ knowledge_wikijs_pgpass }}"

    - name: Deploy WikiJS
      ansible.builtin.import_role:
        name: wikijs
      vars:
        wikijs_user: "{{ knowledge_user }}"
        wikijs_container: wikijs
        wikijs_network: "{{ knowledge_network }}"
        wikijs_db_pass: "{{ knowledge_wikijs_pgpass }}"
