- name: Configure public DNS
  hosts: localhost
  tasks:
    - name: Deploy Cloudflare DNS records
      ansible.builtin.import_role:
        name: cloudflare_dns
  vars:
    cloudflare_dns_zone: '{{ internet_host }}'
    cloudflare_dns_token: 'CF_DNS#mP9$kL5vR3@bN7&xQ4wY8zT6'
    cloudflare_dns_data:
      - record:
        comment: 'VPN Service'
        value: '{{ public_ip }}'
