- name: Configure reverse proxy
  hosts: reverse_proxy
  tasks:
    - name: Deploy Caddy
      ansible.builtin.import_role:
        name: caddy
      vars:
        caddy_user: '{{ reverse_proxy_user }}'
        caddy_lan_prefix: '{{ lan_prefix }}'
        caddy_internet_host: '{{ internet_host }}'
        caddy_services: "{{ anubhavg_services | dict2items  | map(attribute='value') | list }}"
        caddy_container: caddy
        caddy_opt: caddy_opt
        caddy_tls: caddy_tls
        caddy_conf: /etc/Caddyfile
        caddy_internet_facing: false
        caddy_networks: 'host'
        caddy_image: 'caddy-private'
        caddy_extensions:
          - github.com/caddy-dns/cloudflare
          - github.com/corazawaf/coraza-caddy/v2
        caddy_cloudflare_token: 'CF_Token#kN7$pL4vM8@bR2&xQ9wY5zT3'
