- name: Configure streaming virtual machine
  hosts: streaming
  vars:
    streaming_user: streaming
    streaming_music: /var/music
  tasks:
    - name: NFS volumes configuration
      ansible.builtin.import_role:
        name: nfs_client
      vars:
        nfs_client_user: "{{ streaming_user }}"
        nfs_client_mounts:
          { "{{ nas_host }}:{{ nfs_server_data }}/music": "{{ streaming_music }}" }

    - name: Deploy Navidrome
      ansible.builtin.import_role:
        name: navidrome
      vars:
        navidrome_user: "{{ streaming_user }}"
        navidrome_container: navidrome
        navidrome_config: 'navidrome_config'
        navidrome_collection: "{{ streaming_music }}"
        navidrome_lastfm_apikey: 'lastfm-kL8#mN4$pR9@vB2'
        navidrome_lastfm_secret: 'lastfm-sK7#nP5$mB3@vL9'

    - name: Deploy Wazuh agent
      ansible.builtin.import_role:
        name: wazuh_agent
      vars:
        wazuh_agent_version: '4.x'
        wazuh_agent_manager_host: '{{ siem_host }}'
        wazuh_agent_registration_pass: '{{ siem_enrollment_pass }}'
        wazuh_agent_name: 'streaming'
        wazuh_agent_groups: 'internet_facing,trusted'
