- name: Deploy Wazuh Manager Container
  hosts: wazuh_manager
  vars:
    wazuh_user: wazuh
    wazuh_network: wazuh
    wazuh_certs_dir: '/var/wazuh'
    
  tasks:
    - name: Ensure wazuh network exists
      ansible.builtin.import_role:
        name: podman
        tasks_from: network
      vars:
        podman_network: '{{ wazuh_network }}'
        podman_user: '{{ wazuh_user }}'

    - name: Deploy Wazuh manager
      ansible.builtin.import_role:
        name: wazuh_manager
      vars:
        wazuh_manager_user: '{{ wazuh_user }}'
        wazuh_manager_container: 'wazuh_manager'
        wazuh_manager_network: '{{ wazuh_network }}'
        wazuh_manager_hostname: 'wazuh.manager'
        wazuh_manager_agent: '1514'
        wazuh_manager_enrollment: '1515'
        wazuh_manager_syslog: '514'
        wazuh_manager_api: '55000'
        wazuh_manager_version: '4.10.1'
        wazuh_manager_api_configuration_vol: 'wazuh_manager_conf'
        wazuh_manager_etc_vol: 'wazuh_manager_etc'
        wazuh_manager_logs_vol: 'wazuh_manager_logs'
        wazuh_manager_queue_vol: 'wazuh_manager_queue'
        wazuh_manager_var_multigroups_vol: 'wazuh_manager_var_multigroups'
        wazuh_manager_integrations_vol: 'wazuh_manager_integrations'
        wazuh_manager_active_response_vol: 'wazuh_manager_active_response'
        wazuh_manager_agentless_vol: 'wazuh_manager_agentless'
        wazuh_manager_wodles_vol: 'wazuh_manager_wodles'
        wazuh_manager_filebeat_etc_vol: 'wazuh_manager_filebeat_etc'
        wazuh_manager_filebeat_var_vol: 'wazuh_manager_filebeat_var'
        wazuh_manager_ssl_certs_dir: '{{ wazuh_certs_dir }}'
        wazuh_manager_config_dir: '/var/wazuh_manager'
