# General Ansible stuff
ansible_user: rocky
ansible_ssh_private_key_file: ~/.ssh/deepanjali.pem
ansible_python_interpreter: /usr/bin/python3

tz: 'Asia/Kolkata'

# Wazuh specific variables
wazuh_version: "4.10.1"

# Public internet hosts

public_ip: '65.1.148.47'
internet_host: 'example.anubhavg.local'

auth_host: auth

vpn_host: 'vpn'

code_personal_host: personal.code
code_work_host: work.code

remote_host: remote

password_mgr_host: vault

music_host: music

# Private reverse proxy address
private_reverse_proxy: '10.0.4.10'

# anubhavg services definition
anubhavg_services:
  auth:
    name: 'Authentication and SSO'
    host: 'auth'
    ip: '10.0.0.10'
    port: '8081'
    tls: false
    private_proxy: '{{ private_reverse_proxy }}'
  music:
    name: 'Music Streaming'
    host: 'music'
    ip: '10.0.0.19'
    port: '4533'
    tls: false
    private_proxy: '{{ private_reverse_proxy }}'
  vault:
    name: 'Password Manager'
    host: 'vault'
    ip: '10.0.0.10'
    port: '8080'
    tls: false
    private_proxy: '{{ private_reverse_proxy }}'
  code_personal:
    name: 'Personal code-server'
    host: 'personal.code'
    ip: '10.0.8.10'
    port: '8443'
    tls: false
    private_proxy: '{{ private_reverse_proxy }}'
    oauth_proxy:
      ip: '10.0.8.10'
      port: '4181'
  code_work:
    name: 'Work code-server'
    host: 'work.code'
    ip: '10.0.8.10'
    port: '8444'
    tls: false
    private_proxy: '{{ private_reverse_proxy }}'
    oauth_proxy:
      ip: '10.0.8.10'
      port: '4180'
  remote:
    name: 'Bastion WebUI'
    host: 'remote'
    ip: '10.0.1.10'
    port: '8081'
    tls: false
    private_proxy: '{{ private_reverse_proxy }}'
  vpn:
    name: 'Headscale Coordination Server'
    host: 'vpn'
    ip: '{{ public_ip }}'
    port: '8080'
    tls: false

# LAN service DNS prefix
lan_prefix: 'lan'

# SIEM

siem_host: '10.0.0.10'
wazuh_auth_password: 'WZ_Auth#kP9$mN5vR2@bL6&xQ8'
siem_enrollment_pass: "{{ wazuh_auth_password }}"

# OIDC

anubhavg_realm: 'anubhavg'

anubhavg_oidc_provider: keycloak-oidc

code_client: 'code-server-client'
code_secret: 'CODE_Secret#nP7$mK4vL8@bR3&xQ9wZ5'

remote_client: 'remote-access-client'
remote_secret: 'REM_Secret#pL6$nK9vM2@bX4&rQ7wY3'

# NAS Stuff

# TODO improve variable assignment
nas_host: '10.0.11.10'
nfs_server_data: /nas-data
